steps:
- task: securedevelopmentteam.vss-secure-development-tools.build-task-policheck.PoliCheck@2
  displayName: 'Run PoliCheck'
  inputs:
    targetType: F
    targetArgument: '$(Build.SourcesDirectory)'
    optionsFC: 1 # Enable source code comment scanning.
    optionsXS: 1 # Enable subfolder scanning
    optionsUEPATH: '$(Build.SourcesDirectory)\eng\pipelines\resources\policheck_exclusion.xml'