---
parameters:
- name: DisplayName
  type: string
- name: JobTemplate
  type: object

jobs:
- job:
  displayName: ${{ parameters.DisplayName }}
  pool:
    vmImage: 'macOS-latest'
  steps:
  - ${{ parameters.JobTemplate }}
...